### PR TITLE
Update lock files

### PR DESCRIPTION
**Pull request by njpearman**
Whilst working on the exercises for the classes module, both the `package-lock.json` file and the `yarn.lock` file were updated after running the start up commands.

### CODE REVIEW

**Review by davidmillican — COMMENTED** [review]
It looks like `package-lock.json` now has an entire new `packages` key that wasn't there before, and is probably duplicating `yarn.lock`. Do you know what's going on there?

Is there a chance that your local node setup is different to elsewhere or the setup steps were run differently?

**Comment by hcarver** [comment]
Looks like there's an upgrade of `lockfileVersion` from 1 to 2. Will that be backwards compatible for older versions? I'd prefer to stick with version 1 unless there's any doubt, as this repo sometimes gets used outside Docker.

**Comment by njpearman** [comment]
I just ran the instructions in the setup, so:

```
npm install

npm start
```

I then had changes. I get the same lock file changes from the `run_and_install.sh` script.

There's no specific `node`/ `npm` / `yarn`  version mentioned in the setup that I can see and don't know what I should do to suppress updating the files. My system is:

```
➜  modern_js git:(add-module-specific-pages) ✗ node -v
v16.6.1
➜  modern_js git:(add-module-specific-pages) ✗ npm -v 
7.20.3
➜  modern_js git:(add-module-specific-pages) ✗ yarn -v
1.22.11
```

**Comment by njpearman** [comment]
@davidmillican looking into this some more, I think that the yarn lock file is redundant based the setup instructions, which use `npm`. I think this has caught me out before (or perhaps in another repository). I'll remove that as a change (and I think ideally it should be removed if I'm correct about it being unused).

**Comment by hcarver** [comment]
Yep, the `yarn.lock` only exists in case people strongly prefer yarn.

To the question about `npm` versions, I think it's fine to distribute an updated version of the lockfile so long as we have an understanding of what will happen if people try to install it with an older version of `npm`. If it'll stop them accessing the session, then we should probably avoid upgrading, or push everyone to use Docker instead.

**Comment by njpearman** [comment]
Okay, thanks @hcarver . I'll close this PR as I don't want to disturb the setup. I think I'm just expecting behaviour more like `Gemfile.lock` from the lock files; it's just a lack of familiarity on my part...

**Pull request closed without merging**
